resources:
  repositories:
    - repository: templates
      type: github
      name: NSLS-II/profile-collection-ci
      # TODO: change it back to 'refs/heads/main' once
      # https://github.com/NSLS-II/profile-collection-ci/pull/19 is merged.
      ref: refs/heads/add-collection-2021-1.2
      endpoint: github

jobs:
  - template: collection-2021-1.0.yml@templates
    parameters:
      beamline_acronym: PDF
  - template: collection-2021-1.2.yml@templates
    parameters:
      beamline_acronym: PDF
